apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: brivas

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels/topology.kubernetes.io~1region
        value: us-east-ashburn
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 15
    target:
      kind: Deployment
      name: smsc
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 15
    target:
      kind: Deployment
      name: api-gateway

configMapGenerator:
  - name: pop-config
    literals:
      - POP_ID=ashburn
      - LUMADB_PRIMARY=lumadb://lumadb-ashburn-primary.brivas.internal:5432/brivas
      - LUMADB_REPLICAS=lumadb://lumadb-ashburn-replica-1.brivas.internal:5432/brivas
      - STIR_SHAKEN_REQUIRED=true
      - DEFAULT_CURRENCY=USD
      - TIMEZONE=America/New_York
