apiVersion: v2
name: voice-stack
description: Voice Infrastructure Stack - Kamailio SBC, OpenSIPS, FreeSWITCH, rtpengine
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - voip
  - sip
  - ivr
  - kamailio
  - opensips
  - freeswitch
  - rtpengine

maintainers:
  - name: BillyRonks Engineering
    email: engineering@billyronks.com

dependencies:
  - name: common
    version: "1.x.x"
    repository: "file://../common"
    condition: common.enabled
