name: frontend_flutter
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  ferry: ^0.16.0
  gql_http_link: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  ferry_generator: ^0.12.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
