apiVersion: v2
name: cilium-pop
description: Cilium eBPF Load Balancer for Brivas PoP
type: application
version: 1.0.0
appVersion: "1.15.4"

dependencies:
  - name: cilium
    version: "1.15.4"
    repository: https://helm.cilium.io/
