apiVersion: v1
kind: Namespace
metadata:
  name: brivas
  labels:
    app.kubernetes.io/name: brivas
    app.kubernetes.io/part-of: unified-brivas-platform
  annotations:
    kustomize.config.k8s.io/behavior: create
